[package]
name = "py-medmodels"
version = "0.0.1"
edition = "2021"

[lib]
name = "medmodels"
crate-type = ["cdylib"]

[dependencies]
medmodels-core = { workspace = true }
medmodels-utils = { workspace = true }

pyo3 = { version = "0.21.2", features = ["chrono"] }
pyo3-polars = "0.14.0"
polars = { workspace = true }
chrono = { workspace = true }
