[package]
name = "medmodels"
version = "0.0.1"
edition = "2021"

[lib]
name = "medmodels"
crate-type = ["cdylib"]

[dependencies]
petgraph = "0.6.3"
pyo3 = "0.19.0"
numpy = "0.19"
polars = "0.33.2"
pyo3-polars = "0.7.0"
